cleanup

diff --git a/.github/workflows/multi-arch-build.yml b/.github/workflows/multi-arch-build.yml
--- a/.github/workflows/multi-arch-build.yml
+++ b/.github/workflows/multi-arch-build.yml
@@ -3,11 +3,6 @@ name: Multi-Architecture Docker Build
 on:
   workflow_call:
     inputs:
-      registry:
-        description: The registry where the image will be pushed to
-        type: string
-        required: false
-        default: registry.equisoft.io
       aws-region:
         description: AWS region for the registry
         type: string
@@ -51,6 +46,10 @@ on:
         type: boolean
         required: true
         default: false
+      registry:
+        description: The registry where the image will be pushed to
+        type: string
+        required: true
       role-to-assume:
         description: Role to assume that has write access to the registry
         type: string
@@ -70,9 +69,9 @@ on:
         default: "."
 
     outputs:
-      image-version:
-        description: Image version built by this workflow
-        value: ${{ jobs.build.outputs.image-version }}
+      image-id:
+        description: Image ID built by this action
+        value: ${{ jobs.create-manifest.outputs.image-id }}
 
 jobs:
   prepare:
@@ -80,6 +79,7 @@ jobs:
     outputs:
       tags: ${{ steps.metadata.outputs.tags }}
       labels: ${{ steps.metadata.outputs.labels }}
+      annotations: ${{ steps.metadata.outputs.annotations }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -124,7 +124,7 @@ jobs:
         id: build
         uses: equisoft-actions/docker-build-and-push@DOPS-5820/retire-buildx
         with:
-          registry: ${{ inputs.registry }}
+          annotations: ${{ needs.prepare.outputs.annotations }}
           aws-region: ${{ inputs.aws-region }}
           build-args: ${{ inputs.build-args }}
           context: ${{ inputs.context }}
@@ -133,9 +133,10 @@ jobs:
           name: ${{ inputs.name }}
           no-cache: ${{ inputs.no-cache }}
           is-release: ${{ inputs.is-release }}
-          platform: ${{ matrix.platform }}
+          platform: linux/${{ matrix.platform }}
           pull: ${{ inputs.pull }}
           push: ${{ inputs.push }}
+          registry: ${{ inputs.registry }}
           role-to-assume: ${{ inputs.role-to-assume }}
           role-session-name: ${{ inputs.role-session-name }}-${{ matrix.platform }}
           tags: ${{ needs.prepare.outputs.tags }}
@@ -147,6 +148,9 @@ jobs:
     needs:
       - prepare
       - build
+    outputs:
+      image-id: ${{ steps.outputs.outputs.image-id }}
+      image-version: ${{ steps.outputs.outputs.image-version }}
     steps:
       - name: Download digests
         uses: actions/download-artifact@v4
@@ -159,15 +163,16 @@ jobs:
         shell: bash
         id: context
         run: |
-          echo "has-role=${{ inputs.role-to-assume != '' }}" >> $GITHUB_OUTPUT
+          if [[ -z "${{ inputs.role-to-assume }}" && -n "${{ inputs.aws-region }}" ]]; then
+            echo "Error: AWS region is set but role-to-assume is not." >&2
+            exit 1
+          fi
           echo "is-ecr=${{ inputs.aws-region != '' }}" >> $GITHUB_OUTPUT
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         if: steps.context.outputs.is-ecr == 'true'
         with:
-          aws-access-key-id: ${{ steps.context.outputs.has-role != 'true' && inputs.aws-access-key-id || '' }}
-          aws-secret-access-key: ${{ steps.context.outputs.has-role != 'true' && inputs.aws-secret-access-key || '' }}
           aws-region: ${{ inputs.aws-region }}
           role-to-assume: ${{ inputs.role-to-assume }}
           role-session-name: ${{ inputs.role-session-name }}-manifest
@@ -205,3 +210,12 @@ jobs:
               docker buildx imagetools inspect "$tag"
             fi
           done
+
+      - name: Output image tag
+        id: outputs
+        shell: bash
+        run: |
+          IMAGE_TAG=$(cut -d',' -f1 <<<'${{ needs.prepare.outputs.tags }}')
+          IMAGE_VERSION=$(cut -d':' -f2 <<<"${IMAGE_TAG}")
+          echo "image-version=${IMAGE_VERSION}" >> $GITHUB_OUTPUT
+          echo "image-id=${IMAGE_TAG}" >> $GITHUB_OUTPUT
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -4,14 +4,11 @@ description: Build a container image and optionally push it. Labels and tags wil
 inputs:
   registry:
     description: The registry where the image will be pushed to.
+    required: true
+  annotations:
+    description: Annotations to apply to the image, in the format 'key=value,key2=value2'.
     required: false
-    default: registry.equisoft.io
-  aws-access-key-id:
-    description: DEPRECATED. Use `role-to-assume` instead. An AWS access key ID that has write permissions to the registry.
-    required: false
-  aws-secret-access-key:
-    description: An AWS secret access key that has write permissions to the registry.
-    required: false
+    default: ""
   aws-region:
     description: AWS region for the registry.
     required: false
@@ -35,20 +32,13 @@ inputs:
     description: Labels to apply to the image, in the format 'key=value,key2=value2'.
     required: false
     default: ""
-  name:
-    description: A simple name for this image
-    required: true
   no-cache:
     description: Do not use cache when building the image (default false)
     required: false
     default: "false"
-  is-release:
-    description: if this build is a production release
-    required: false
-    default: "false"
-  platform:
-    description: The target platform for the image, e.g., 'amd64,arm64'.
-    required: false
+  platforms:
+    description: The target platform for the image, e.g., 'linux/amd64,linux/arm64'.
+    required: true
   pull:
     description: Always attempt to pull all referenced images (default false)
     required: false
@@ -65,11 +55,7 @@ inputs:
     required: false
   tags:
     description: Comma-separated list of tags to apply to the image.
-    required: false
-    default: ""
-  version:
-    description: The SemVer compatible version for this image, without prefixes.
-    required: true
+    required: tr
   working-directory:
     description: >-
       Relative path under $GITHUB_WORKSPACE where the project is located.
@@ -81,9 +67,6 @@ outputs:
   image-id:
     description: Image ID built by this action
     value: ${{ steps.build-push.outputs.imageid }}
-  image-version:
-    description: Image version built by this action
-    value: ${{ steps.build-push.outputs.image-version }}
 
 runs:
   using: composite
@@ -92,7 +75,10 @@ runs:
       shell: bash
       id: context
       run: |
-        echo "has-role=${{ inputs.role-to-assume != '' }}" >> $GITHUB_OUTPUT
+        if [[ -z "${{ inputs.role-to-assume }}" && -n "${{ inputs.aws-region }}" ]]; then
+          echo "Error: AWS region is set but role-to-assume is not." >&2
+          exit 1
+        fi
         echo "is-ecr=${{ inputs.aws-region != '' }}" >> $GITHUB_OUTPUT
         new_tags=$(echo "${{ inputs.tags }}" | tr ',' '\n' | sed "s/$/-${{ inputs.platform }}/" | paste -sd ',')
         echo "tags=${new_tags}" >> $GITHUB_OUTPUT
@@ -101,8 +87,6 @@ runs:
       uses: aws-actions/configure-aws-credentials@v4
       if: steps.context.outputs.is-ecr == 'true'
       with:
-        aws-access-key-id: ${{ steps.context.outputs.has-role != 'true' && inputs.aws-access-key-id || '' }}
-        aws-secret-access-key: ${{ steps.context.outputs.has-role != 'true' && inputs.aws-secret-access-key || '' }}
         aws-region: ${{ inputs.aws-region }}
         role-to-assume: ${{ inputs.role-to-assume }}
         role-session-name: ${{ inputs.role-session-name }}
@@ -111,6 +95,15 @@ runs:
       uses: aws-actions/amazon-ecr-login@v2
       if: steps.context.outputs.is-ecr == 'true'
 
+    - name: Set up QEMU
+      uses: docker/setup-qemu-action@v3
+      # if inputs.platforms contains more than one platform, this step is required to enable multi-arch builds
+      if: contains(inputs.platforms, ',')
+      with:
+        # see: https://github.com/tonistiigi/binfmt/issues/215
+        # see: https://github.com/docker/setup-qemu-action/issues/198
+        image: tonistiigi/binfmt:qemu-v7.0.0-28
+
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v3
 
@@ -118,10 +111,12 @@ runs:
       id: build-push
       uses: docker/build-push-action@v6
       env:
-        DOCKER_BUILD_SUMMARY: ${{ inputs.build-summary == 'true' || 'false' }}
+        DOCKER_BUILD_SUMMARY: ${{ inputs.build-summary }}
       with:
+        annotations: ${{ inputs.annotations }}
         build-args: |
           ${{ inputs.build-args }}
+          BUILDKIT_MULTI_PLATFORM=1
         context: ${{ inputs.context }}
         file: ${{ inputs.working-directory }}/${{ inputs.dockerfile }}
         labels: ${{ inputs.labels }}
@@ -129,7 +124,7 @@ runs:
         provenance: false
         pull: ${{ inputs.pull == 'true' }}
         push: ${{ inputs.push == 'true' }}
-        platforms: linux/${{ inputs.platform }}
+        platforms: ${{ inputs.platforms }}
         tags: ${{ steps.context.outputs.tags }}
 
     - name: Export digest
